"""Runtime cross-package import gate (auto-generated).

Generated by `scitex-dev ecosystem write-integration-tests`.
Hand edits inside the AUTO-GENERATED block will be overwritten on
regeneration; add hand-written cases below the second sentinel.

This test imports every cross-package module that 'scitex-container' references
in its source tree. Two outcomes:

- Module installed AND import succeeds → test PASSES.
- Module installed BUT import fails (e.g. internal rename like
  `scitex_io._load_cache` → `scitex_io._loading._load_cache`) →
  test FAILS loudly.
- Peer package NOT installed at all (standalone absent in a lean CI
  env, optional extra, marker-gated dependency) → test is SKIPPED.

The skip is taken on the ROOT package only (`pytest.importorskip` on
`name.split(".")[0]`); the FULL dotted path is then hard-imported with
`importlib.import_module`. Skipping on the full path would swallow the
one failure this gate exists to catch — a renamed submodule of an
INSTALLED peer raises ModuleNotFoundError just like an absent peer,
so `importorskip(full_path)` reports the rename as green (PS-140).
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    "scitex_config",
    "scitex_config._ecosystem",
    "scitex_dev",
    "scitex_dev._cli._completion",
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import(module_name):
    """Importing scitex-container's declared cross-package dependency must succeed."""
    # Arrange
    # (parametrized module_name is the input)
    # Act
    # Skip only when the PEER ITSELF is absent — judged on the root package.
    pytest.importorskip(module_name.split(".")[0])
    # The full dotted path is a hard import: a renamed submodule now FAILS.
    module = importlib.import_module(module_name)
    # Assert
    assert module is not None
